CREATE TABLE Customers (
    CustomerID NUMBER PRIMARY KEY,
    Name VARCHAR2(100),
    DateOfBirth DATE,
    Balance NUMBER,
    IsVIP VARCHAR2(10) DEFAULT 'FALSE',
    LastModified DATE
);

CREATE TABLE Accounts (
    AccountID NUMBER PRIMARY KEY,
    CustomerID NUMBER REFERENCES Customers(CustomerID),
    AccountType VARCHAR2(20),
    Balance NUMBER
);

CREATE TABLE Loans (
    LoanID NUMBER PRIMARY KEY,
    CustomerID NUMBER REFERENCES Customers(CustomerID),
    PrincipalAmount NUMBER,
    InterestRate NUMBER,
    EndDate DATE
);

CREATE TABLE Employees (
    EmployeeID NUMBER PRIMARY KEY,
    Name VARCHAR2(100),
    Department VARCHAR2(50),
    Salary NUMBER
);

CREATE TABLE Transactions (
    TransactionID NUMBER PRIMARY KEY,
    AccountID NUMBER REFERENCES Accounts(AccountID),
    TransactionDate DATE,
    Amount NUMBER,
    TransactionType VARCHAR2(20)
);

CREATE TABLE AuditLog (
    LogID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TransactionID NUMBER,
    AccountID NUMBER,
    TransactionDate DATE,
    Amount NUMBER,
    TransactionType VARCHAR2(20),
    LogDate DATE
);

INSERT INTO Customers (CustomerID, Name, DateOfBirth, Balance, IsVIP, LastModified)
VALUES (1, 'Alice Smith', '1955-06-15', 12000, 'FALSE', CURRENT_DATE);

INSERT INTO Customers (CustomerID, Name, DateOfBirth, Balance, IsVIP, LastModified)
VALUES (2, 'Bob Johnson', '1985-03-22', 8500, 'FALSE', CURRENT_DATE);

INSERT INTO Customers (CustomerID, Name, DateOfBirth, Balance, IsVIP, LastModified)
VALUES (3, 'John Miller', '1960-11-05', 15000, 'FALSE', CURRENT_DATE);

INSERT INTO Accounts (AccountID, CustomerID, AccountType, Balance)
VALUES (101, 1, 'Savings', 12000);

INSERT INTO Accounts (AccountID, CustomerID, AccountType, Balance)
VALUES (102, 2, 'Checking', 8500);

INSERT INTO Accounts (AccountID, CustomerID, AccountType, Balance)
VALUES (103, 3, 'Savings', 15000);

INSERT INTO Loans (LoanID, CustomerID, PrincipalAmount, InterestRate, EndDate)
VALUES (501, 1, 50000, 7.5, CURRENT_DATE + 15);

INSERT INTO Loans (LoanID, CustomerID, PrincipalAmount, InterestRate, EndDate)
VALUES (502, 2, 15000, 8.0, CURRENT_DATE + 45);

INSERT INTO Loans (LoanID, CustomerID, PrincipalAmount, InterestRate, EndDate)
VALUES (503, 3, 20000, 6.5, CURRENT_DATE + 10);

INSERT INTO Employees (EmployeeID, Name, Department, Salary)
VALUES (1001, 'Charlie Brown', 'IT', 75000);

INSERT INTO Employees (EmployeeID, Name, Department, Salary)
VALUES (1002, 'Diana Prince', 'HR', 65000);

COMMIT;
